#!/usr/bin/expect

log_user 0

# For user name and password
source [file dirname [info script]]/../config/config.tcl

exp_spawn telnet $hostname

expect "Please login: "
send "$username\r"
expect "Please Enter password: "
send "$password\r"

expect "rsc> "
send "poweroff\r"
expect "Are you sure you want to turn your system power off (Yes/No)?  "
send "yes\r"
expect "rsc> "
send "logout\r"

exit


